## Basic Python

1. Split this *string*`

In [ ]:
c = "Hi there Sam !"
print("List of words after splitting:",c.split(" "))

List of words after splitting: ['Hi', 'there', 'Sam', '!']


2. Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
Planet = "Earth"
Diameter = 12742
print("The diameter of {} is {} kilometers.".format(Planet,Diameter))

The diameter of Earth is 12742 kilometers.


3. In this nest dictionary grab the word hello

In [ ]:
d = {"k1":[1,2,3,{"tricky":["oh", "man", "inception",{"target":[1,2,3,"hello"]}]}]}
print(d["k1"][3]["tricky"][3]["target"][3])

hello


## Numpy

4.1 Create an array of 10 zeros

In [ ]:
import numpy as np

In [ ]:
arr1 = np.zeros(10)
print("Array of 10 zeros:",arr1)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 Create an array of 10 fives

In [ ]:
arr2 = 5*np.ones(10)
print("Array of 10 fives:",arr2)

Array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [ ]:
a = 20
b = 35
arr3 = []
for i in range(a,b+1):
  if (i%2==0):
    arr3.append(i)
print("The required array:",arr3)

The required array: [20, 22, 24, 26, 28, 30, 32, 34]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
n = 8
mat = np.arange(0,n+1)
mat = mat.reshape(3,3)
print("Matrix:\n",mat)

Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate a and b

   a = np.array([1,2,3]), b = np.array([4,5,6])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print("Concatenated Array:\n",c)

Concatenated Array:
 [1 2 3 4 5 6]


## Pandas

8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [ ]:
import random
l1=[]
for i in range(6):
  a = random.randint(0,6)
  l1.append(a)
l1 = np.array(l1)
data = l1.reshape(3,2)
df1 = pd.DataFrame(data,columns=["A","B"],index=["C","D","E"])
df1

A  B
C  0  3
D  3  6
E  5  0

9. Generate the series of dates from 1st Jan,2023 to 10th Feb,2023

In [ ]:
pd.date_range(start="1-1-2023", end="10-02-2023", freq="2D")

DatetimeIndex(['2023-01-01', '2023-01-03', '2023-01-05', '2023-01-07',
               '2023-01-09', '2023-01-11', '2023-01-13', '2023-01-15',
               '2023-01-17', '2023-01-19',
               ...
               '2023-09-14', '2023-09-16', '2023-09-18', '2023-09-20',
               '2023-09-22', '2023-09-24', '2023-09-26', '2023-09-28',
               '2023-09-30', '2023-10-02'],
              dtype='datetime64[ns]', length=138, freq='2D')

10. Create 2D list to DataFrame

In [ ]:
l2 = [[1,2,3],[4,5,6],[7,8,9]]
df2 = pd.DataFrame(l2)
df2

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9